/* ------------------------------------------------------------------ */
/*  Shared domain types for the study planner                          */
/* ------------------------------------------------------------------ */

/** How often a task repeats */
export type Frequency = "once" | "daily" | "weekly";

/**
 * "fixed"    → happens at a specific time (tuition class, school, exam)
 * "flexible" → the auto-scheduler finds free time for it
 */
export type TaskKind = "fixed" | "flexible";

/** Detected/declared "this task IS a past paper" metadata */
export interface PaperMeta {
  year: number;
  paperType: PaperType;
  part?: PaperPart;
}

export interface Task {
  id: string;
  name: string;
  notes?: string;
  subject: string; // subject id
  estimatedMinutes: number;
  /** when set, the task is mirrored into the Past Paper vault */
  paperMeta?: PaperMeta;
  /** id of the PastPaper record this task created */
  linkedPaperId?: string;
  /** yyyy-mm-dd — the due date for "once", the event date for fixed one-offs */
  deadline: string;
  frequency: Frequency;
  /** 0 = Sunday … 6 = Saturday (only used when frequency === "weekly") */
  weeklyDays: number[];
  kind: TaskKind;
  /** "HH:MM" — only for fixed tasks */
  startTime?: string;
  endTime?: string;
  completed: boolean;
  createdAt: number;
  completedAt?: number;
}

/** A concrete block of time on the calendar (generated by the scheduler) */
export interface Session {
  id: string;
  taskId: string;
  taskName: string;
  subject: string;
  /** yyyy-mm-dd */
  date: string;
  /** minutes from midnight */
  start: number;
  end: number;
  kind: TaskKind;
  /** true when placed automatically by the scheduling engine */
  auto: boolean;
  done: boolean;
}

export type PaperType = "MCQ" | "Structured" | "Essay";
export type PaperStatus = "planned" | "completed";
/** A/L papers are sat in two parts — Paper I (usually MCQ) & Paper II */
export type PaperPart = "I" | "II";

export interface PastPaper {
  id: string;
  subject: string;
  year: number;
  paperType: PaperType;
  /** undefined = full / single paper */
  part?: PaperPart;
  status: PaperStatus;
  /** percentage 0–100 (only when completed) */
  score?: number;
  /** yyyy-mm-dd — when it was / will be attempted */
  date: string;
}

export interface Subject {
  id: string;
  name: string;
  short: string;
  color: string;
  /** excluded from study-time analytics (e.g. school hours) */
  excluded?: boolean;
}

/** Aggregated study minutes: studyLog[date][subjectId] = minutes */
export type StudyLog = Record<string, Record<string, number>>;

export interface Prefs {
  theme: "dark" | "light";
  wellness: boolean;
}

/** Everything that gets persisted (localStorage + RTDB) */
export interface PersistedState {
  tasks: Task[];
  papers: PastPaper[];
  subjects: Subject[];
  doneSessions: Record<string, boolean>;
  studyLog: StudyLog;
  prefs: Prefs;
}

/** Input accepted by the add/edit task modal */
export type TaskInput = Omit<Task, "id" | "createdAt" | "completed" | "completedAt">;

export type View = "dashboard" | "calendar" | "tasks" | "papers" | "analytics";

export interface Toast {
  id: string;
  icon: "water" | "break" | "stretch" | "check" | "info" | "sparkle";
  title: string;
  body?: string;
}
